# Generated by Django 3.2.5 on 2021-11-30 07:57

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('routine', '0002_alter_routine_create_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='routine',
            name='create_date',
            field=models.DateTimeField(default=datetime.datetime(2021, 11, 30, 16, 57, 5, 267188)),
        ),
    ]
