# Generated by Django 3.2.5 on 2021-12-09 14:57

import datetime
from django.db import migrations, models
import django_mysql.models


class Migration(migrations.Migration):

    dependencies = [
        ('routine', '0004_alter_routine_create_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='routine',
            name='create_date',
            field=models.DateTimeField(default=datetime.datetime(2021, 12, 9, 23, 57, 42, 610651)),
        ),
        migrations.AlterField(
            model_name='routine',
            name='cron',
            field=django_mysql.models.ListTextField(models.IntegerField(), size=100),
        ),
        migrations.AlterField(
            model_name='routine',
            name='log_id',
            field=django_mysql.models.ListTextField(models.IntegerField(), size=100),
        ),
    ]
