# Generated by Django 3.2.5 on 2021-12-13 16:46

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('routine', '0006_auto_20211213_0219'),
    ]

    operations = [
        migrations.AlterField(
            model_name='routine',
            name='create_date',
            field=models.DateTimeField(default=datetime.datetime(2021, 12, 14, 1, 46, 31, 273943)),
        ),
    ]
