# Generated by Django 3.2.5 on 2021-12-12 17:19

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diary', '0005_alter_diary_diary_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='diary',
            name='diary_date',
            field=models.DateTimeField(default=datetime.datetime(2021, 12, 13, 2, 19, 11, 768153)),
        ),
    ]
