# Generated by Django 3.2.5 on 2021-12-13 16:46

import datetime
from django.db import migrations, models
import django_mysql.models


class Migration(migrations.Migration):

    dependencies = [
        ('diary', '0006_alter_diary_diary_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='diary',
            name='diary_date',
            field=models.DateTimeField(default=datetime.datetime(2021, 12, 14, 1, 46, 31, 272943)),
        ),
        migrations.AlterField(
            model_name='diary',
            name='log_id',
            field=django_mysql.models.ListTextField(models.IntegerField(), null=True, size=None),
        ),
    ]
