# Generated by Django 3.2.5 on 2021-12-13 16:46

from django.db import migrations, models
import django_mysql.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Flower',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_date', models.DateTimeField(auto_now_add=True)),
                ('update_date', models.DateTimeField(auto_now=True)),
                ('title', models.TextField()),
                ('grade', models.IntegerField()),
                ('step', models.IntegerField()),
                ('color', models.TextField()),
                ('log_id', django_mysql.models.ListTextField(models.IntegerField(), null=True, size=None)),
                ('event_id', django_mysql.models.ListTextField(models.IntegerField(), null=True, size=None)),
                ('user_id', models.IntegerField()),
            ],
            options={
                'db_table': 'flower',
            },
        ),
    ]
